### ISSUE TITLE
Bad UX in code

### ISSUE THREAD

**Issue by orenty7** [aslanchek/Passholder#3]
Program should check that storage exist before asking password. 

https://github.com/aslanchek/Passholder/blob/4847bb72376da881c1ee877da0a95ae0a3e3059f/controller.py#L26-L31

**Comment by aslanchek** [comment]
soglasen, seichas popravlu

**Comment by Arslan223** [comment]
> soglasen, seichas popravlu

я уже фикшу

**Comment by aslanchek** [comment]
а э нуу

**Comment by Arslan223** [comment]
https://github.com/aslanchek/Passholder/pull/10

**Comment by aslanchek** [comment]
fixed with new program structure (see dev branch)
