### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by orenty7** [aslanchek/Passholder#7]
https://github.com/aslanchek/Passholder/blob/4847bb72376da881c1ee877da0a95ae0a3e3059f/interface.py#L2-L3

![image](https://user-images.githubusercontent.com/20957455/167299841-534d9b3f-c34b-44fc-8559-66d8d88bf2a5.png)

**Comment by aslanchek** [comment]
Just checked that this class is alive... Fixed.
